name: 23f1002563@ds.study.iitm.ac.in 

on:
  schedule:
    - cron: '50 6 * * *'  # Runs daily at 05:30 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub-provided token for authentication

      - name: 23f1002563@ds.study.iitm.ac.in  # Step with your email
        run: echo "Automated daily commit workflow running"

      - name: Update log file
        run: |
          echo "Last run: $(date -u)" >> update.log

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add update.log
          git commit -m "Automated commit: $(date -u)"
          git push origin main
