name: Daily Commit Action

on:
  schedule:
    - cron: '39 6 * * *'  # Runs daily at 5:30 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23f1002563@ds.study.iitm.ac.in  # Step with email
        run: echo "Running scheduled commit action"

      - name: Update log file
        run: |
          echo "Last run: $(date -u)" >> update.log

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add update.log
          git commit -m "Automated commit: $(date -u)"
          git push
